SELECT * FROM FRAUD_LABELS;
SELECT * FROM MERCHANTS;
SELECT * FROM TRANSACTIONS;
SELECT * FROM USERS;

-- Null check: USERS
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(*) - COUNT(USER_ID) AS USER_ID_NULLS,
    COUNT(*) - COUNT(AGE_GROUP) AS AGE_GROUP_NULLS,
    COUNT(*) - COUNT(CITY) AS CITY_NULLS,
    COUNT(*) - COUNT(CITY_TIER) AS CITY_TIER_NULLS,
    COUNT(*) - COUNT(KYC_STATUS) AS KYC_STATUS_NULLS,
    COUNT(*) - COUNT(ACCOUNT_AGE_DAYS) AS ACCOUNT_AGE_DAYS_NULLS,
    COUNT(*) - COUNT(LINKED_BANK_COUNT) AS LINKED_BANK_COUNT_NULLS,
    COUNT(*) - COUNT(AVG_MONTHLY_TRANSACTIONS) AS AVG_MONTHLY_TRANSACTIONS_NULLS,
    COUNT(*) - COUNT(AVG_TRANSACTION_VALUE) AS AVG_TRANSACTION_VALUE_NULLS,
    COUNT(*) - COUNT(PREFERRED_APP) AS PREFERRED_APP_NULLS,
    COUNT(*) - COUNT(PREFERRED_DEVICE) AS PREFERRED_DEVICE_NULLS,
    COUNT(*) - COUNT(USER_LOYALTY_SCORE) AS USER_LOYALTY_SCORE_NULLS,
    COUNT(*) - COUNT(IS_HIGH_RISK_USER) AS IS_HIGH_RISK_USER_NULLS
FROM UPI_TRANSACTIONS_DB.PUBLIC.USERS;

-- Null check: TRANSACTIONS
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(*) - COUNT(TRANSACTION_ID) AS TRANSACTION_ID_NULLS,
    COUNT(*) - COUNT(USER_ID) AS USER_ID_NULLS,
    COUNT(*) - COUNT(RECEIVER_ID) AS RECEIVER_ID_NULLS,
    COUNT(*) - COUNT(RECEIVER_TYPE) AS RECEIVER_TYPE_NULLS,
    COUNT(*) - COUNT(AMOUNT) AS AMOUNT_NULLS,
    COUNT(*) - COUNT(TIMESTAMP) AS TIMESTAMP_NULLS,
    COUNT(*) - COUNT(DATE) AS DATE_NULLS,
    COUNT(*) - COUNT(HOUR_OF_DAY) AS HOUR_OF_DAY_NULLS,
    COUNT(*) - COUNT(DAY_OF_WEEK) AS DAY_OF_WEEK_NULLS,
    COUNT(*) - COUNT(IS_WEEKEND) AS IS_WEEKEND_NULLS,
    COUNT(*) - COUNT(IS_NIGHT_TRANSACTION) AS IS_NIGHT_TRANSACTION_NULLS,
    COUNT(*) - COUNT(TIME_SINCE_LAST_TXN_MIN) AS TIME_SINCE_LAST_TXN_MIN_NULLS,
    COUNT(*) - COUNT(TRANSACTION_TYPE) AS TRANSACTION_TYPE_NULLS,
    COUNT(*) - COUNT(PAYMENT_APP) AS PAYMENT_APP_NULLS,
    COUNT(*) - COUNT(DEVICE_TYPE) AS DEVICE_TYPE_NULLS,
    COUNT(*) - COUNT(STATUS) AS STATUS_NULLS,
    COUNT(*) - COUNT(USER_CITY_TIER) AS USER_CITY_TIER_NULLS,
    COUNT(*) - COUNT(USER_KYC_STATUS) AS USER_KYC_STATUS_NULLS,
    COUNT(*) - COUNT(USER_AVG_MONTHLY_TXN) AS USER_AVG_MONTHLY_TXN_NULLS,
    COUNT(*) - COUNT(USER_AVG_TXN_VALUE) AS USER_AVG_TXN_VALUE_NULLS,
    COUNT(*) - COUNT(USER_LOYALTY_SCORE) AS USER_LOYALTY_SCORE_NULLS,
    COUNT(*) - COUNT(NEW_DEVICE_FLAG) AS NEW_DEVICE_FLAG_NULLS,
    COUNT(*) - COUNT(IP_LOCATION_MISMATCH) AS IP_LOCATION_MISMATCH_NULLS,
    COUNT(*) - COUNT(FAILED_ATTEMPTS_LAST_24H) AS FAILED_ATTEMPTS_LAST_24H_NULLS,
    COUNT(*) - COUNT(TRANSACTION_VELOCITY) AS TRANSACTION_VELOCITY_NULLS,
    COUNT(*) - COUNT(AMOUNT_DEVIATION_SCORE) AS AMOUNT_DEVIATION_SCORE_NULLS,
    COUNT(*) - COUNT(IS_FRAUD) AS IS_FRAUD_NULLS,
    COUNT(*) - COUNT(RECURRING_PAYMENT_FLAG) AS RECURRING_PAYMENT_FLAG_NULLS,
    COUNT(*) - COUNT(BALANCE_AFTER_TRANSACTION) AS BALANCE_AFTER_TRANSACTION_NULLS,
    COUNT(*) - COUNT(TRANSACTION_FREQUENCY_SCORE) AS TRANSACTION_FREQUENCY_SCORE_NULLS
FROM UPI_TRANSACTIONS_DB.PUBLIC.TRANSACTIONS;

-- Null check: FRAUD_LABELS
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(*) - COUNT(TRANSACTION_ID) AS TRANSACTION_ID_NULLS,
    COUNT(*) - COUNT(USER_ID) AS USER_ID_NULLS,
    COUNT(*) - COUNT(RECEIVER_ID) AS RECEIVER_ID_NULLS,
    COUNT(*) - COUNT(AMOUNT) AS AMOUNT_NULLS,
    COUNT(*) - COUNT(TIMESTAMP) AS TIMESTAMP_NULLS,
    COUNT(*) - COUNT(IS_FRAUD) AS IS_FRAUD_NULLS,
    COUNT(*) - COUNT(NEW_DEVICE_FLAG) AS NEW_DEVICE_FLAG_NULLS,
    COUNT(*) - COUNT(IP_LOCATION_MISMATCH) AS IP_LOCATION_MISMATCH_NULLS,
    COUNT(*) - COUNT(FAILED_ATTEMPTS_LAST_24H) AS FAILED_ATTEMPTS_LAST_24H_NULLS,
    COUNT(*) - COUNT(TRANSACTION_VELOCITY) AS TRANSACTION_VELOCITY_NULLS,
    COUNT(*) - COUNT(AMOUNT_DEVIATION_SCORE) AS AMOUNT_DEVIATION_SCORE_NULLS
FROM UPI_TRANSACTIONS_DB.PUBLIC.FRAUD_LABELS;

-- Null check: MERCHANTS
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(*) - COUNT(MERCHANT_ID) AS MERCHANT_ID_NULLS,
    COUNT(*) - COUNT(MERCHANT_NAME) AS MERCHANT_NAME_NULLS,
    COUNT(*) - COUNT(MERCHANT_CATEGORY) AS MERCHANT_CATEGORY_NULLS,
    COUNT(*) - COUNT(MERCHANT_SIZE) AS MERCHANT_SIZE_NULLS,
    COUNT(*) - COUNT(CITY) AS CITY_NULLS,
    COUNT(*) - COUNT(CITY_TIER) AS CITY_TIER_NULLS,
    COUNT(*) - COUNT(AVG_DAILY_TRANSACTIONS) AS AVG_DAILY_TRANSACTIONS_NULLS,
    COUNT(*) - COUNT(IS_REGISTERED) AS IS_REGISTERED_NULLS,
    COUNT(*) - COUNT(RATING) AS RATING_NULLS
FROM UPI_TRANSACTIONS_DB.PUBLIC.MERCHANTS;

--handle Null Values Present in the tables- 'Fraud_labels' & 'Transactions'
UPDATE TRANSACTIONS
SET TIME_SINCE_LAST_TXN_MIN =0 WHERE TIME_SINCE_LAST_TXN_MIN IS NULL;

UPDATE TRANSACTIONS
SET TRANSACTION_VELOCITY=(SELECT MEDIAN(TRANSACTION_VELOCITY) FROM TRANSACTIONS) WHERE TRANSACTION_VELOCITY IS NULL;

UPDATE TRANSACTIONS
SET AMOUNT_DEVIATION_SCORE=(SELECT MEDIAN(AMOUNT_DEVIATION_SCORE) FROM TRANSACTIONS) WHERE AMOUNT_DEVIATION_SCORE IS NULL;

UPDATE FRAUD_LABELS
SET TRANSACTION_VELOCITY=(SELECT MEDIAN(TRANSACTION_VELOCITY) FROM FRAUD_LABELS) WHERE TRANSACTION_VELOCITY IS NULL;

UPDATE FRAUD_LABELS
SET AMOUNT_DEVIATION_SCORE=(SELECT MEDIAN(AMOUNT_DEVIATION_SCORE) FROM FRAUD_LABELS) WHERE AMOUNT_DEVIATION_SCORE IS NULL;

--Duplicate Record Check
SELECT USER_ID, COUNT(*)
FROM USERS
GROUP BY USER_ID
HAVING COUNT(*) >1;

SELECT TRANSACTION_ID, COUNT(*)
FROM TRANSACTIONS
GROUP BY TRANSACTION_ID
HAVING COUNT(*) >1;

SELECT TRANSACTION_ID, COUNT(*)
FROM FRAUD_LABELS
GROUP BY TRANSACTION_ID
HAVING COUNT(*) >1;

SELECT MERCHANT_ID, COUNT(*)
FROM MERCHANTS
GROUP BY MERCHANT_ID
HAVING COUNT(*) >1;

--Invalid Value Checks
SELECT* FROM TRANSACTIONS
WHERE AMOUNT<=0;                        --Negative or Zero Transaction Amount

SELECT* FROM TRANSACTIONS
WHERE TIMESTAMP> CURRENT_TIMESTAMP;     --Future Timestamp Check

SELECT DISTINCT STATUS
FROM TRANSACTIONS                       --Invalid Transaction Status

SELECT DISTINCT AGE_GROUP 
FROM USERS                              --Invalid Age Values

SELECT DISTINCT IS_FRAUD
FROM FRAUD_LABELS                       --Invalid Fraud Labels
                                        
--Outlier Detection
SELECT MIN(AMOUNT) min_amount, AVG(AMOUNT) avg_amount, MAX(AMOUNT) max_amount
FROM TRANSACTIONS

SELECT MIN(TRANSACTION_VELOCITY) min_velocity, AVG(TRANSACTION_VELOCITY) avg_velocity, MAX(TRANSACTION_VELOCITY) max_velocity
FROM TRANSACTIONS

SELECT MIN(AMOUNT_DEVIATION_SCORE) min_score, AVG(AMOUNT_DEVIATION_SCORE) avg_score, MAX(AMOUNT_DEVIATION_SCORE) max_score
FROM TRANSACTIONS

--For ER Diagram / Relationships--> Define Primary & Foreign Keys
ALTER TABLE USERS
ADD PRIMARY KEY (USER_ID);

ALTER TABLE TRANSACTIONS
ADD PRIMARY KEY (TRANSACTION_ID);

ALTER TABLE MERCHANTS
ADD PRIMARY KEY (MERCHANT_ID);

ALTER TABLE TRANSACTIONS
ADD FOREIGN KEY (RECEIVER_ID)
REFERENCES USERS(USER_ID);

ALTER TABLE FRAUD_LABELS
ADD FOREIGN KEY (TRANSACTION_ID)
REFERENCES TRANSACTIONS(TRANSACTION_ID);